language: java
jdk: openjdk8

before_install: . ./.travis.env.sh

deploy:
  provider: script
  script: ./.travis-deploy.sh -s .travis.settings.xml
  skip_cleanup: true
  on:
    branch: master

before_cache:
  - rm -rf ~/.m2/repository/org/opencast/annotate
  - sudo chown -R travis:travis ~/.m2

cache:
  directories:
    - $HOME/.m2
    - frontend/node
    - frontend/node_modules
