name: Deploy Maven artifacts
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Check out the m2 repository
        uses: actions/checkout@v2
        with:
          ref: m2
          path: m2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            frontend/node
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: Build and deploy
        run: mvn clean install -Dopencast.version="[8,9-SNAPSHOT)" --batch-mode
